#!/usr/bin/env python3
# 销售十坑 · 字幕：cn 默认 = whisper 逐字原话(RAW)，FIX 只改同音错字/分句。
# 纪律：贴录音，翻拍稿只在 ASR garbled 时兜底。EN 是翻译(非逐字)。
import json, pathlib
HERE = pathlib.Path('.')
RAW = json.load(open('groups.raw.json'))
def cjk(s): return sum(1 for c in s if '一' <= c <= '鿿') or len(s)

# 只改这些：同音错字 + 把含两句的段用 | 切开。其余一律用 RAW 原话。
FIX = {
 1: "我最近在给美国的律所当 FDE|也就是 Forward Deployed Engineer",
 3: "扎进客户现场的部署工程师",
 4: "天天把 AI 塞进人家的业务里做自动化",
 11: "被灌的那套销售观念",
 14: "一个一个给你刨出来",
 16: "看看你中了几个|中得越多,越得看完",
 22: "build 的一个东西越来越便宜|一个智能体",
 23: "可能一个晚上就给你糊出来了",
 28: "其实本质上就是 sell 加交付|干得越久",
 30: "就是销售的底层根本不是话术",
 31: "恰恰是那些把话术当做命根子的人",
 34: "迷信话术和技巧",
 39: "比任何推销话术都管用|其实你想想",
 42: "立刻竖起一道防线|其实大家都一样",
 45: "找过来想要做 AI 自动化",
 50: "我说这套 ROI 太低了|我不能卖给你",
 56: "这玩意是靠话术骗不来的|然后第二个坑",
 58: "在聪明人面前耍套路|这是我其实",
 59: "最有感触的一条|因为你越是",
 61: "你越要说大实话|那些销售课可能教你的话术",
 65: "其实跟过家家一样|一眼就看穿",
 66: "对付聪明人|其实唯一的办法就是有一说一",
 71: "或者说一个简单的商业模型",
 73: "对方自然就知道你有真东西|第三个坑",
 80: "一直扑上去绝不放弃|在今天",
 82: "纳瓦尔说的挺好|他说这个时代",
 87: "然后继续往前走就可以了|因为世界很大",
 89: "那个能产生共鸣的人|把死缠烂打",
 95: "在情绪里跟人对线",
 98: "纳瓦尔给了一个特别好的词",
 99: "叫理性的同理心|意思就是说交流的时候",
 107: "其实就是那个 yes and",
 113: "这条我自己其实也常踩",
 116: "纳瓦尔这条我太喜欢了",
 128: "你看到的世界会清晰 100 倍|第六个坑",
 129: "把我说话直当个性来标榜|总有人说",
 130: "我这个人就是直不会拐弯",
 131: "对不起你那个不叫直",
 132: "你这叫情商低|所以纳瓦尔说",
 144: "你想帮他|照顾别人的体面",
 145: "你的真话才有力量|第七个坑",
 151: "身边还有 AI 这么能干的东西|你再拿鞭子抽",
 153: "其实没用了|纳瓦尔说",
 160: "和你想做的事拧到一起",
 161: "找到那个重合点|你不用赶",
 162: "他们自己会往前去冲的|第八个坑是",
 163: "找合伙人只看能力|不看信任和目标",
 173: "一起分这头大象|举个例子",
 174: "我跟我的一个合伙人|我们有一天晚上",
 175: "从横滨一路喝到东京|边走边聊",
 183: "后面一切才变得简单|第九个坑",
 185: "最不在乎的东西|这是最大的坑",
 188: "把这支笔卖给我|纳瓦尔说",
 194: "我现在在 all in 做一个产品叫做 Hedj|我先不细说",
 197: "建立你自己的职业护城河|为什么是我做",
 198: "因为它就是我的血和肉|我自己就是那个",
 202: "我根本不需要任何销售技巧|因为我是真的信",
 204: "满到溢出来",
 207: "对方自己就会想买|促成合作",
 210: "我觉得是在蝇头小利上死磕|为了和气",
 211: "把烂交易也签了|我们活在一个",
 219: "一千倍空间的事上|最重要的是",
 220: "保持选择权|如果一个合作",
 221: "你闻出来是一个长期的坑|投资人也好",
 224: "把这单搅黄|也别为了一句",
 225: "没事咱们一起弄吧|委屈签字",
 226: "一旦你妥协签了字|后面有你受的",
 228: "是做成一家好公司的天敌|OK",
 229: "所以这十个坑过完了|你回头看",
 233: "是只卖你真信的东西|是做长远的事",
 241: "而我现在在做 Hedj",
 242: "做的就是这件事|帮你在 AI 把一切 build",
 245: "AI 也替不掉的职业护城河|所以评论区",
 249: "是你自己真信的东西吗",
}

# META[i] = (en, style, hl, enhl)；split 组用 | 对齐 FIX 的切分
META = [
 ("hey everyone","a","",""),
 ("lately I've been an FDE for US law firms|that is, a Forward Deployed Engineer","a|a","FDE","FDE"),
 ("in plain words","a","",""),
 ("an engineer embedded on-site with clients","a","",""),
 ("shoving AI into their business all day, automating it","a","AI","AI"),
 ("and I just happened to come across","a","",""),
 ("a Naval episode all about","a","纳瓦尔","Naval"),
 ("how to sell things","a","",""),
 ("listened to it on a run","a","",""),
 ("and it really got to me","a","",""),
 ("because I realized most of us","a","",""),
 ("were fed a set of sales beliefs","a","",""),
 ("and ten out of ten are traps","b","10个有10个","ten out of ten"),
 ("today I'll dig out all 10 traps","a","10个坑","10 traps"),
 ("one by one","a","",""),
 ("check yourself as you listen","a","",""),
 ("see how many you've hit|the more you hit, the more you need to finish","a|b","",""),
 ("first, something counterintuitive","a","",""),
 ("the essence of a company is selling","b","销售","selling"),
 ("you hear 'sales'","a","",""),
 ("and picture a guy downstairs pushing cards","a","",""),
 ("but in the AI era","a","AI","AI"),
 ("building something keeps getting cheaper|one agent","a|a","build","build"),
 ("can hack it out in a night","a","",""),
 ("what's actually scarce","a","",""),
 ("is selling it","a","",""),
 ("getting someone to pay for it","a","",""),
 ("what I do on-site every day","a","",""),
 ("is basically sell plus deliver|the longer I do it","a|a","sell","sell"),
 ("the surer I am of one thing","a","",""),
 ("selling, at its core, isn't tricks at all","b","话术","tricks"),
 ("it's exactly the people who live by tricks","a","话术","tricks"),
 ("who hit the first trap","a","第一个坑","first trap"),
 ("so, the first trap, I think","a","",""),
 ("worshipping tricks and tactics","a","",""),
 ("thinking polished scripts close deals","a","",""),
 ("Naval put it well, actually","a","纳瓦尔","Naval"),
 ("I think","a","",""),
 ("he says: a solid reputation","b","信誉","reputation"),
 ("beats any sales pitch|think about it","b|a","",""),
 ("the second you sense a pitch","a","",""),
 ("your first reaction","a","",""),
 ("is to throw up a wall|everyone's the same","a|a","",""),
 ("let me tell you something that happened to me","a","",""),
 ("last month a small US law firm","a","",""),
 ("came wanting AI automation","a","AI","AI"),
 ("I looked around at their workflow","a","",""),
 ("really simple, just a few forms","a","",""),
 ("automating it saves barely any time","a","",""),
 ("so I told the boss straight","a","",""),
 ("the ROI is too low|I can't sell you this","b|a","ROI","ROI"),
 ("lost a deal on the spot","a","",""),
 ("but two weeks later he took someone he knew","a","",""),
 ("a big firm's boss, and introduced him to me","a","",""),
 ("so trust is, in the business world","a","信任","trust"),
 ("the most valuable pass there is","b","",""),
 ("you can't fake it with tricks|so, trap two","a|b","话术","tricks"),
 ("I think is","a","",""),
 ("running games on smart people|this is the one","b|a","",""),
 ("the one I feel the most|because the more you","a|a","",""),
 ("deal with the sharpest people","a","",""),
 ("the more you tell the plain truth|those sales-course tricks","b|a","大实话","plain truth"),
 ("mind games","a","",""),
 ("'last two spots today'","a","",""),
 ("to a high-awareness person","a","",""),
 ("look like a kid's game|seen through instantly","a|b","",""),
 ("with smart people, the only move|is straight talk","a|b","",""),
 ("no lying","a","",""),
 ("always aim for win-win, but first","a","双赢","win-win"),
 ("your fundamentals have to be solid","a","",""),
 ("able to take a simple piece of tech","a","",""),
 ("or a simple business model","a","",""),
 ("and explain it in the plainest words","a","",""),
 ("they just know you've got the real thing|trap three","a|b","",""),
 ("I think is","a","",""),
 ("getting rejected and clinging on","a","",""),
 ("and calling it 'hustle'","a","",""),
 ("people used to preach that sales","a","",""),
 ("needs a wolf's hustle","a","",""),
 ("rejected? no problem, keep calling","a","",""),
 ("pounce and never give up|but today","a|a","",""),
 ("this, I think, is a big trap","b","",""),
 ("Naval nailed it|he says, these days","a|a","纳瓦尔","Naval"),
 ("everyone's time is brutally expensive","a","",""),
 ("you pitch an idea, a project","a","",""),
 ("they hear it and feel nothing","a","",""),
 ("just smile, shake hands","a","",""),
 ("and move on|because the world is big","a|a","",""),
 ("you'll always find","a","",""),
 ("the one who resonates|the energy you'd waste clinging","a|a","",""),
 ("save it","a","",""),
 ("give it to the right people","a","",""),
 ("that's the most efficient play","b","",""),
 ("then, trap four, I think is","a","",""),
 ("rushing to argue the second you talk","a","",""),
 ("fighting people from inside your emotions","a","",""),
 ("nine times out of ten, conflict happens","a","",""),
 ("because both sides soak in their own emotion","a","",""),
 ("Naval gave a great word for it","a","纳瓦尔","Naval"),
 ("rational compassion|it means, when you talk","b|a","理性的同理心","rational compassion"),
 ("set your emotion aside first","a","",""),
 ("reason through it","a","",""),
 ("why does the other person think this","a","",""),
 ("if he's making sense, don't rush to rebut","a","",""),
 ("first openly grant him: you're right","a","你说的对","you're right"),
 ("and then, on that basis","a","",""),
 ("calmly explain why your stance also holds","a","",""),
 ("it's basically that 'yes, and'","a","yes and","yes and"),
 ("agree first, then build on it","a","",""),
 ("that's how the other person can actually hear you","a","",""),
 ("then trap five","b","",""),
 ("when you make decisions","a","",""),
 ("getting hijacked by face and self-interest","a","",""),
 ("I step on this one a lot myself","a","",""),
 ("when we advise or decide","a","",""),
 ("it's so easy to get pulled by 'my face, my gain'","a","",""),
 ("this Naval one I love","a","纳瓦尔","Naval"),
 ("he says, be as objective as you can","a","",""),
 ("take face and ego out of the conversation","b","自我","ego"),
 ("so imagine","a","",""),
 ("if it were someone with","a","",""),
 ("zero stake in this thing","a","",""),
 ("how would they advise","a","",""),
 ("that advice is usually the right one","a","",""),
 ("I've found a pattern","a","",""),
 ("the heavier your ego","a","",""),
 ("the less you can sell","a","",""),
 ("strip the ego out","a","",""),
 ("the world you see gets 100x clearer|trap six","b|b","100倍","100x"),
 ("flaunting 'I'm blunt' as a personality|people always say","a|a","",""),
 ("I'm just direct, I don't sugarcoat","a","",""),
 ("sorry, that's not directness","a","",""),
 ("you call it low EQ|so Naval says","b|a","情商低","low EQ"),
 ("the essence of charisma is","a","魅力","charisma"),
 ("honesty plus kindness","b","诚实;善良","honesty;kindness"),
 ("strength married to goodwill","a","",""),
 ("if you've only got honesty","a","",""),
 ("with zero grace","a","",""),
 ("out of self-protection","a","",""),
 ("they won't hear your truth at all","a","",""),
 ("so real charisma is: you tell the truth","a","",""),
 ("while the other person genuinely feels","a","",""),
 ("that you point out their problem","a","",""),
 ("because you care about them","b","在乎","care"),
 ("you want to help them|honor the other's dignity","a|a","",""),
 ("and your truth has power|trap seven","a|b","",""),
 ("running a pack of smart people with KPIs and a whip","a","KPI","KPIs"),
 ("in the factory age","a","",""),
 ("managing meant barking orders","a","",""),
 ("here's a task, go do it now","a","",""),
 ("but today you lead smart people","a","",""),
 ("with AI this capable around|crack the whip again","a|a","AI","AI"),
 ("dangle the big pie","a","",""),
 ("and it's useless|Naval says","a|a","纳瓦尔","Naval"),
 ("management is giving orders","a","",""),
 ("leadership is igniting people's inner desire","b","领导力","leadership"),
 ("you sit down and listen to your team","a","",""),
 ("your partners","a","",""),
 ("what they truly want from this life","a","",""),
 ("then take their personal goals","a","",""),
 ("and twist them together with yours","a","",""),
 ("find the overlap|you won't have to push","a|a","",""),
 ("they'll charge ahead on their own|trap eight is","a|b","",""),
 ("picking partners only on skill|not on trust and goals","a|b","信任","trust"),
 ("we all know","a","",""),
 ("for tens of thousands of years","a","",""),
 ("humans survived in small hunting tribes","a","",""),
 ("to hunt one elephant together","a","",""),
 ("you must be able to give them your back","b","",""),
 ("or one knife from behind and you're dead too","a","",""),
 ("business today is identical","a","",""),
 ("you want each person owning their lane","a","",""),
 ("solving the hard thing together","a","",""),
 ("and sharing the elephant|for example","a|a","",""),
 ("me and one of my partners|one night","a|a","",""),
 ("drank our way from Yokohama to Tokyo|talking as we walked","b|a","横滨;东京","Yokohama;Tokyo"),
 ("about AI and the future of humanity","a","AI","AI"),
 ("talked till it was almost dawn","a","",""),
 ("that night I knew this guy's solid","b","",""),
 ("trusting him with my back is no problem","a","",""),
 ("so picking a cofounder","a","",""),
 ("really is like finding a partner","b","",""),
 ("only when goals twist together","a","",""),
 ("does everything later get simple|trap nine","a|b","",""),
 ("I think is selling something you don't even believe in","a","",""),
 ("don't even care about|this is the biggest trap","a|b","",""),
 ("old sellers love The Wolf of Wall Street","a","",""),
 ("right off the bat it's","a","",""),
 ("sell me this pen|Naval says","a|a","纳瓦尔","Naval"),
 ("that test itself is nonsense","a","",""),
 ("it has you pitch something you feel nothing for","a","",""),
 ("totally unrelated to you","a","",""),
 ("he says, only sell what you truly love","b","真正热爱","truly love"),
 ("what you're truly obsessed with","a","",""),
 ("I'm all in on a product called Hedj|I won't get into","a|a","Hedj","Hedj"),
 ("what exactly it does, just know","a","",""),
 ("it helps you, in this AI era","a","AI","AI"),
 ("build your own career moat|why me","b|a","护城河","moat"),
 ("because it's my flesh and blood|I'm the one","b|a","",""),
 ("forced by AI","a","AI","AI"),
 ("to go find a new moat","a","护城河","moat"),
 ("so when I talk to you about it","a","",""),
 ("I need zero sales tricks|because I truly believe","a|b","",""),
 ("when your conviction in something","a","",""),
 ("overflows","b","",""),
 ("you're just honestly sharing","a","",""),
 ("your passion and certainty","a","",""),
 ("and they just want to buy|closing the deal","b|a","",""),
 ("becomes effortless, a natural result","a","",""),
 ("trap ten","b","",""),
 ("I think is grinding over crumbs|and for harmony's sake","a|a","蝇头小利","crumbs"),
 ("signing the bad deal too|we live in an age","a|a","",""),
 ("of highly nonlinear returns","b","非线性","nonlinear"),
 ("you do a hundred things","a","一百件","a hundred"),
 ("and one or two bring the real payoff","a","一两件","one or two"),
 ("so don't, on those","a","",""),
 ("fly-leg-sized scraps","a","",""),
 ("haggle with people endlessly","a","",""),
 ("aim at the things with 100x","a","一百倍","100x"),
 ("1000x of upside|and most important","a|a","一千倍","1000x"),
 ("keep your optionality|if a deal","b|a","选择权","optionality"),
 ("you smell as a long-term trap|an investor","a|a","",""),
 ("a partner, acting really dirty","a","",""),
 ("then you'd rather grit your teeth","a","",""),
 ("and blow up the deal|than, for one line","a|a","",""),
 ("'it's fine, let's do it together'|sign against yourself","a|a","",""),
 ("once you compromise and sign|you'll pay for it later","a|a","",""),
 ("this spineless compromise","a","",""),
 ("is the natural enemy of a good company|okay","b|a","",""),
 ("so that's all 10 traps|look back","a|a","十个坑","10 traps"),
 ("and you'll find they reduce to one line","a","",""),
 ("stop worshipping tricks and scripts","b","",""),
 ("real selling is trust, is honesty","a","信任;真诚","trust;honesty"),
 ("is selling only what you believe|is playing the long game","a|a","",""),
 ("honestly","a","",""),
 ("whether it's business","a","",""),
 ("or anything else","a","",""),
 ("the bottom line is the same","a","",""),
 ("right people, honest words, the long game","b","",""),
 ("you never lacked tricks","a","",""),
 ("you lacked knowing the bottom line","a","",""),
 ("and what I'm building now, Hedj","a","Hedj","Hedj"),
 ("does exactly this|helping you, now that AI makes all building","a|a","AI","AI"),
 ("dirt cheap","a","",""),
 ("build a moat no one can take","a","",""),
 ("and AI can't replace, a career moat|so in the comments","b|a","护城河","moat"),
 ("let's talk","a","",""),
 ("how many of the 10 traps did you hit","b","",""),
 ("and the thing you most want to sell","a","",""),
 ("is it something you truly believe in","b","",""),
]

assert len(META) == len(RAW), f"META {len(META)} != RAW {len(RAW)}"

out = []
for i, raw in enumerate(RAW):
    cn = FIX.get(i, raw['cn'])
    en, style, hl, enhl = META[i]
    s0, e0 = raw['start'], raw['end']
    cn_parts = cn.split('|')
    if len(cn_parts) == 1:
        o = {"start": s0, "end": e0, "cn": cn, "en": en, "style": style}
        if hl: o["hl"] = hl.split(';')
        if enhl: o["enhl"] = enhl.split(';')
        out.append(o)
    else:
        en_p = en.split('|'); st_p = style.split('|')
        hl_p = hl.split('|') if '|' in hl else [hl, ""]
        enhl_p = enhl.split('|') if '|' in enhl else [enhl, ""]
        weights = [cjk(p) for p in cn_parts]; tot = sum(weights) or 1
        t = s0
        for k, p in enumerate(cn_parts):
            seg = (e0 - s0) * weights[k] / tot
            ps, pe = round(t, 2), round(t + seg, 2)
            if k == len(cn_parts) - 1: pe = e0
            t = pe
            o = {"start": ps, "end": pe, "cn": p, "en": en_p[k] if k < len(en_p) else "",
                 "style": st_p[k] if k < len(st_p) else "a"}
            h = hl_p[k] if k < len(hl_p) else ""; eh = enhl_p[k] if k < len(enhl_p) else ""
            if h: o["hl"] = h.split(';')
            if eh: o["enhl"] = eh.split(';')
            out.append(o)

pathlib.Path('groups.full.json').write_text(json.dumps(out, ensure_ascii=False, indent=1), encoding='utf-8')
print(f'wrote groups.full.json: {len(out)} caps, dur {out[-1]["end"]}')
